package dev.huyghe.morseflashlight.data;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.util.Objects;

/**
 * DB object to represent a message that a user may want to communicate using the app.
 */
@Entity(indices = {@Index("timesUsed")})
public class Message {
    @PrimaryKey(autoGenerate = true)
    final int id;
    @NonNull
    final String content;
    final int timesUsed;

    public Message(@NonNull String content, int timesUsed) {
        this.id = 0; // Autogenerated id, 0 == not set, we want to leave this for SQLite to fill.
        this.content = content;
        this.timesUsed = timesUsed;
    }

    /**
     * Simple id.
     */
    public int getId() {
        return id;
    }

    /**
     * The message itself.
     */
    @NonNull
    public String getContent() {
        return content;
    }

    /**
     * The number of times this message was flashed.
     * For sorting purposes.
     */
    public int getTimesUsed() {
        return timesUsed;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Message)) return false;
        Message message = (Message) o;
        return getId() == message.getId() && getTimesUsed() == message.getTimesUsed() && getContent().equals(message.getContent());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getContent(), getTimesUsed());
    }

    @NonNull
    @Override
    public String toString() {
        return "Message{" +
                "id=" + id +
                ", content='" + content + '\'' +
                ", timesUsed=" + timesUsed +
                '}';
    }
}
